// swift-tools-version:5.9
// Generated by SwiftFlowKit

import PackageDescription

let package = Package(
    name: "NnLocalNotificationKit",
    products: [
        .library(
            name: "NnLocalNotificationKit",
            targets: ["NnLocalNotificationKit"]
        ),
    ],
    dependencies: [
    ],
    targets: [
        .target(
            name: "NnLocalNotificationKit",
            dependencies: [
            ]
        ),
    ]
)
